# Generated by Django 5.2.8 on 2025-11-13 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cuit', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('condicion_fiscal', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MO', 'Monotributista'), ('EX', 'Exento'), ('CF', 'Consumidor Final')], max_length=2)),
                ('punto_venta', models.CharField(default='0001', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=10)),
                ('descripcion', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cuit', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('descripcion_larga', models.TextField(blank=True)),
                ('stock', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('stock_maximo', models.IntegerField(default=0)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_efectivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_tarjeta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_ctacte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_lista4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrar.marca')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrar.proveedor')),
                ('rubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrar.rubro')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrar.provincia')),
            ],
            options={
                'unique_together': {('provincia', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_cliente', models.CharField(choices=[('P', 'Persona'), ('E', 'Empresa')], default='P', max_length=1)),
                ('cuit', models.CharField(blank=True, max_length=20)),
                ('condicion_fiscal', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MT', 'Monotributo'), ('CF', 'Consumidor Final'), ('EX', 'Exento'), ('NC', 'No Categorizado')], default='CF', max_length=2)),
                ('domicilio', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('lista_precio', models.CharField(choices=[('1', 'Lista 1'), ('2', 'Lista 2'), ('3', 'Lista 3'), ('4', 'Lista 4')], default='1', max_length=1)),
                ('tipo_factura_preferida', models.CharField(default='B', max_length=1)),
                ('descuento_predeterminado', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vendedor_asignado', models.CharField(blank=True, max_length=100)),
                ('tiene_ctacte', models.BooleanField(default=False)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('permitir_superar_limite', models.BooleanField(default=False)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_ultima_compra', models.DateField(blank=True, null=True)),
                ('total_compras_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('contacto_nombre', models.CharField(blank=True, max_length=100)),
                ('contacto_telefono', models.CharField(blank=True, max_length=30)),
                ('contacto_email', models.CharField(blank=True, max_length=100)),
                ('rubro_cliente', models.CharField(blank=True, max_length=100)),
                ('canal', models.CharField(blank=True, choices=[('MIN', 'Minorista'), ('MAY', 'Mayorista'), ('DIST', 'Distribuidor'), ('ONL', 'Online')], max_length=4)),
                ('origen', models.CharField(blank=True, choices=[('WEB', 'Web'), ('WSP', 'WhatsApp'), ('RED', 'Redes Sociales'), ('REF', 'Recomendado'), ('OTR', 'Otro')], max_length=4)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('motivo_baja', models.TextField(blank=True)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrar.localidad')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrar.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_comprobante', models.CharField(choices=[('A', 'Factura A'), ('B', 'Factura B'), ('C', 'Factura C')], max_length=2)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cae', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(default='Emitida', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrar.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrar.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='administrar.venta')),
            ],
        ),
    ]
