# Generated by Django 5.2.8 on 2025-11-13 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0003_compra_detallecompra_movimientostock_ordencompra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCuentaCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('DEBE', 'Debe'), ('HABER', 'Haber')], max_length=10)),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrar.cliente')),
            ],
        ),
    ]
