# Generated by Django 5.2.8 on 2025-11-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0004_movimientocuentacorriente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_inicial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_bulto',
            field=models.CharField(choices=[('UN', 'Unidad'), ('CJ', 'Caja'), ('PA', 'Paquete'), ('LT', 'Litros'), ('KG', 'Kilogramos'), ('MT', 'Metros')], default='UN', max_length=2),
        ),
    ]
