# Generated by Django 5.2.8 on 2025-11-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0005_producto_stock_inicial_producto_tipo_bulto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_bulto',
            field=models.CharField(default='UN', max_length=5),
        ),
    ]
