# Generated by Django 5.2.8 on 2025-11-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0007_pedido_detallepedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='lista_precio',
            field=models.CharField(choices=[('1', 'Efectivo / Contado'), ('2', 'Cuenta Corriente'), ('3', 'Tarjeta'), ('4', 'Mayorista')], default='1', max_length=1),
        ),
    ]
