# Generated by Django 5.2.8 on 2025-11-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0008_alter_cliente_lista_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubro',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
