# Generated by Django 5.2.8 on 2025-11-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0009_rubro_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
