# Generated by Django 5.2.8 on 2025-11-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0010_marca_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
