# Generated by Django 5.2.8 on 2025-11-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0011_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidad',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
    ]
