# Generated by Django 5.2.8 on 2025-11-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0012_localidad_codigo_postal_alter_provincia_nombre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localidad',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='codigo_postal',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='nombre',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='provincia',
        ),
    ]
