# Generated by Django 5.2.8 on 2025-11-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0013_alter_localidad_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
