# Generated by Django 5.2.8 on 2025-11-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0014_alter_localidad_codigo_postal'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Plantilla Predeterminada', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='invoice_logos/')),
                ('header_html', models.TextField(blank=True, help_text='HTML para la cabecera de la factura')),
                ('footer_html', models.TextField(blank=True, help_text='HTML para el pie de página de la factura')),
                ('css', models.TextField(blank=True, help_text='CSS personalizado para la factura')),
                ('active', models.BooleanField(default=False, help_text='Si está activo, esta plantilla se usará por defecto')),
            ],
        ),
    ]
