# Generated by Django 5.2.8 on 2025-12-02 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0015_invoicetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: Ejercicio 2025', max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cerrado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=200)),
                ('numero', models.IntegerField(help_text='Número correlativo dentro del ejercicio')),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('VENTAS', 'Ventas'), ('COMPRAS', 'Compras'), ('COBROS', 'Cobros'), ('PAGOS', 'Pagos'), ('APERTURA', 'Apertura'), ('CIERRE', 'Cierre')], default='MANUAL', max_length=10)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, default='Sistema', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrar.ejerciciocontable')),
            ],
            options={
                'ordering': ['-fecha', '-numero'],
                'unique_together': {('ejercicio', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='PlanCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: 1.1.01.001', max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PN', 'Patrimonio Neto'), ('R_POS', 'Resultado Positivo'), ('R_NEG', 'Resultado Negativo')], max_length=10)),
                ('imputable', models.BooleanField(default=True, help_text='Si es True, recibe asientos. Si es False, es rubro agrupador.')),
                ('nivel', models.IntegerField(default=1)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='administrar.plancuenta')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ItemAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('descripcion', models.CharField(blank=True, help_text='Detalle opcional de la línea', max_length=200)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='administrar.asiento')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrar.plancuenta')),
            ],
        ),
    ]
