# Generated by Django 5.2.8 on 2025-12-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0016_ejerciciocontable_asiento_plancuenta_itemasiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='certificado_afip',
            field=models.FileField(blank=True, null=True, upload_to='afip/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='clave_privada_afip',
            field=models.FileField(blank=True, null=True, upload_to='afip/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='moneda_predeterminada',
            field=models.CharField(choices=[('ARS', 'Peso Argentino'), ('USD', 'Dólar')], default='ARS', max_length=3),
        ),
        migrations.AddField(
            model_name='empresa',
            name='papel_impresion',
            field=models.CharField(choices=[('A4', 'A4'), ('T80', 'Ticket 80mm'), ('T58', 'Ticket 58mm')], default='A4', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pie_factura',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='empresa',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='empresa',
            name='smtp_security',
            field=models.CharField(choices=[('STARTTLS', 'STARTTLS'), ('SSL', 'SSL')], default='STARTTLS', max_length=10),
        ),
        migrations.AddField(
            model_name='empresa',
            name='smtp_server',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='smtp_user',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_facturacion',
            field=models.CharField(choices=[('AFIP', 'AFIP Electrónica'), ('FISCAL', 'Impresora Fiscal'), ('MANUAL', 'Factura Manual')], default='AFIP', max_length=20),
        ),
    ]
