# Generated by Django 5.2.8 on 2025-12-03 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0017_empresa_certificado_afip_empresa_clave_privada_afip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceso_ventas', models.BooleanField(default=False, verbose_name='Acceso a Ventas')),
                ('acceso_compras', models.BooleanField(default=False, verbose_name='Acceso a Compras')),
                ('acceso_productos', models.BooleanField(default=False, verbose_name='Acceso a Productos')),
                ('acceso_clientes', models.BooleanField(default=False, verbose_name='Acceso a Clientes')),
                ('acceso_proveedores', models.BooleanField(default=False, verbose_name='Acceso a Proveedores')),
                ('acceso_caja', models.BooleanField(default=False, verbose_name='Acceso a Caja')),
                ('acceso_contabilidad', models.BooleanField(default=False, verbose_name='Acceso a Contabilidad')),
                ('acceso_configuracion', models.BooleanField(default=False, verbose_name='Acceso a Configuración')),
                ('acceso_usuarios', models.BooleanField(default=False, verbose_name='Acceso a Usuarios')),
                ('acceso_reportes', models.BooleanField(default=False, verbose_name='Acceso a Reportes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
