# Generated by Django 5.2.8 on 2025-12-04 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0018_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión Activa',
                'verbose_name_plural': 'Sesiones Activas',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Modificación'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('PASSWORD_CHANGE', 'Cambio de contraseña'), ('SESSION_CLOSE', 'Cierre de sesión remoto'), ('OTHER', 'Otro')], max_length=20)),
                ('module', models.CharField(choices=[('PRODUCTOS', 'Productos'), ('VENTAS', 'Ventas'), ('COMPRAS', 'Compras'), ('CLIENTES', 'Clientes'), ('PROVEEDORES', 'Proveedores'), ('USUARIOS', 'Usuarios'), ('CAJA', 'Caja'), ('CONTABILIDAD', 'Contabilidad'), ('CONFIGURACION', 'Configuración'), ('SEGURIDAD', 'Seguridad'), ('SISTEMA', 'Sistema')], max_length=20)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, help_text='Detalles adicionales en formato JSON', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Nombre de usuario intentado', max_length=150)),
                ('ip_address', models.GenericIPAddressField(help_text='Dirección IP del cliente')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False, help_text='Si el login fue exitoso')),
                ('user_agent', models.TextField(blank=True, help_text='User agent del navegador')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario (null si el intento falló)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Login',
                'verbose_name_plural': 'Historial de Logins',
                'ordering': ['-timestamp'],
            },
        ),
    ]
