# Generated by Django 5.2.8 on 2025-12-05 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0019_activesession_activitylog_loginhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del backup', max_length=255)),
                ('archivo', models.CharField(help_text='Ruta del archivo de backup', max_length=500)),
                ('tamanio', models.BigIntegerField(help_text='Tamaño en bytes')),
                ('ubicacion', models.CharField(choices=[('LOCAL', 'Disco Local'), ('USB', 'Pendrive/USB'), ('NUBE', 'Nube')], default='LOCAL', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del backup')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
