# Generated by Django 5.2.8 on 2025-12-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0020_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='tipo',
            field=models.CharField(choices=[('DB', 'Base de Datos'), ('SISTEMA', 'Archivos de Sistema')], default='DB', max_length=10),
        ),
    ]
