# Generated by Django 5.2.8 on 2025-12-05 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0021_backup_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_comprobante', models.CharField(choices=[('NCA', 'Nota Crédito A'), ('NCB', 'Nota Crédito B'), ('NCC', 'Nota Crédito C')], max_length=3)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cae', models.CharField(blank=True, max_length=20, null=True)),
                ('motivo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=10)),
                ('punto_venta', models.CharField(default='0001', max_length=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrar.cliente')),
                ('venta_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito', to='administrar.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleNotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrar.producto')),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='administrar.notacredito')),
            ],
        ),
        migrations.CreateModel(
            name='NotaDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_comprobante', models.CharField(choices=[('NDA', 'Nota Débito A'), ('NDB', 'Nota Débito B'), ('NDC', 'Nota Débito C')], max_length=3)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cae', models.CharField(blank=True, max_length=20, null=True)),
                ('motivo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=10)),
                ('punto_venta', models.CharField(default='0001', max_length=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrar.cliente')),
                ('venta_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_debito', to='administrar.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleNotaDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrar.producto')),
                ('nota_debito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='administrar.notadebito')),
            ],
        ),
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('direccion_entrega', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('GENERADO', 'Generado'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('ANULADO', 'Anulado')], default='GENERADO', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('punto_venta', models.CharField(default='0001', max_length=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrar.cliente')),
                ('venta_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remitos', to='administrar.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRemito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrar.producto')),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='administrar.remito')),
            ],
        ),
    ]
