# Generated by Django 5.2.8 on 2025-12-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0022_notacredito_detallenotacredito_notadebito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='iibb',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ingresos Brutos'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='inicio_actividades',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de Actividades'),
        ),
    ]
