# Generated by Django 5.2.8 on 2025-12-06 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0023_empresa_iibb_empresa_inicio_actividades'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activesession',
            options={'ordering': ['-last_activity'], 'verbose_name': 'SesiÃ³n Activa', 'verbose_name_plural': 'Sesiones Activas'},
        ),
        migrations.AddField(
            model_name='remito',
            name='alcance',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='remito',
            name='cuit_transportista',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='remito',
            name='denominacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Denominacion y Capacidad'),
        ),
        migrations.AddField(
            model_name='remito',
            name='maq',
            field=models.CharField(blank=True, max_length=50, verbose_name='M.A.Q.'),
        ),
        migrations.AddField(
            model_name='remito',
            name='material',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='remito',
            name='ocm',
            field=models.CharField(blank=True, max_length=50, verbose_name='O.C.M.'),
        ),
        migrations.AddField(
            model_name='remito',
            name='orden_compra',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='remito',
            name='pedido_interno',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='remito',
            name='proyecto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='remito',
            name='transportista',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'CreaciÃ³n'), ('UPDATE', 'ModificaciÃ³n'), ('DELETE', 'EliminaciÃ³n'), ('LOGIN', 'Inicio de sesiÃ³n'), ('LOGOUT', 'Cierre de sesiÃ³n'), ('PASSWORD_CHANGE', 'Cambio de contraseÃ±a'), ('SESSION_CLOSE', 'Cierre de sesiÃ³n remoto'), ('OTHER', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='module',
            field=models.CharField(choices=[('PRODUCTOS', 'Productos'), ('VENTAS', 'Ventas'), ('COMPRAS', 'Compras'), ('CLIENTES', 'Clientes'), ('PROVEEDORES', 'Proveedores'), ('USUARIOS', 'Usuarios'), ('CAJA', 'Caja'), ('CONTABILIDAD', 'Contabilidad'), ('CONFIGURACION', 'ConfiguraciÃ³n'), ('SEGURIDAD', 'Seguridad'), ('SISTEMA', 'Sistema')], max_length=20),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='numero',
            field=models.IntegerField(help_text='NÃºmero correlativo dentro del ejercicio'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='descripcion',
            field=models.TextField(blank=True, help_text='DescripciÃ³n opcional del backup'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='tamanio',
            field=models.BigIntegerField(help_text='TamaÃ±o en bytes'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='moneda_predeterminada',
            field=models.CharField(choices=[('ARS', 'Peso Argentino'), ('USD', 'DÃ³lar')], default='ARS', max_length=3),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_facturacion',
            field=models.CharField(choices=[('AFIP', 'AFIP ElectrÃ³nica'), ('FISCAL', 'Impresora Fiscal'), ('MANUAL', 'Factura Manual')], default='AFIP', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicetemplate',
            name='active',
            field=models.BooleanField(default=False, help_text='Si estÃ¡ activo, esta plantilla se usarÃ¡ por defecto'),
        ),
        migrations.AlterField(
            model_name='invoicetemplate',
            name='footer_html',
            field=models.TextField(blank=True, help_text='HTML para el pie de pÃ¡gina de la factura'),
        ),
        migrations.AlterField(
            model_name='itemasiento',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Detalle opcional de la lÃ\xadnea', max_length=200),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='DirecciÃ³n IP del cliente'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario (null si el intento fallÃ³)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='tipo_comprobante',
            field=models.CharField(choices=[('NCA', 'Nota CrÃ©dito A'), ('NCB', 'Nota CrÃ©dito B'), ('NCC', 'Nota CrÃ©dito C')], max_length=3),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='tipo_comprobante',
            field=models.CharField(choices=[('NDA', 'Nota DÃ©bito A'), ('NDB', 'Nota DÃ©bito B'), ('NDC', 'Nota DÃ©bito C')], max_length=3),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREPARACION', 'En preparaciÃ³n'), ('LISTO', 'Listo para entregar'), ('FACTURADO', 'Facturado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='acceso_configuracion',
            field=models.BooleanField(default=False, verbose_name='Acceso a ConfiguraciÃ³n'),
        ),
    ]
