# Generated by Django 5.2.8 on 2025-12-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0024_alter_activesession_options_remito_alcance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='habilita_remitos',
            field=models.BooleanField(default=True, verbose_name='Habilitar Remitos'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='localidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='provincia',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
