# Generated by Django 5.2.8 on 2025-12-06 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0025_empresa_habilita_remitos_empresa_localidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='pedido_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_generadas', to='administrar.pedido'),
        ),
    ]
