# Generated by Django 5.2.8 on 2025-12-06 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0026_venta_pedido_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('banco', models.CharField(max_length=100)),
                ('fecha_emision', models.DateField()),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('PROPIO', 'Propio'), ('TERCERO', 'Tercero')], default='TERCERO', max_length=10)),
                ('estado', models.CharField(choices=[('CARTERA', 'En Cartera'), ('DEPOSITADO', 'Depositado'), ('COBRADO', 'Cobrado'), ('ENTREGADO', 'Entregado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='CARTERA', max_length=15)),
                ('firmante', models.CharField(blank=True, help_text='Nombre de quien entrega el cheque', max_length=150)),
                ('cuit_firmante', models.CharField(blank=True, max_length=20)),
                ('destinatario', models.CharField(blank=True, help_text='A quien se entrega', max_length=150)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='administrar.cliente')),
            ],
        ),
    ]
