# Generated by Django 5.2.8 on 2025-12-06 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0027_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='saldo_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='MovimientoCuentaCorrienteProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('DEBE', 'Debe'), ('HABER', 'Haber')], max_length=10)),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrar.proveedor')),
            ],
        ),
    ]
