# Generated by Django 5.2.8 on 2025-12-08 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0028_proveedor_saldo_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocuentacorriente',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_cc', to='administrar.venta'),
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor')], max_length=10)),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('anulado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='administrar.cliente')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='administrar.proveedor')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemRecibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('TRANSFERENCIA', 'Transferencia'), ('DEBITO', 'Tarjeta de Débito'), ('CREDITO', 'Tarjeta de Crédito'), ('OTRO', 'Otro')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('referencia', models.CharField(blank=True, help_text='Número de operación, comprobante, etc.', max_length=100)),
                ('cheque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_recibo', to='administrar.cheque')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='administrar.recibo')),
            ],
            options={
                'verbose_name': 'Item de Recibo',
                'verbose_name_plural': 'Items de Recibo',
            },
        ),
        migrations.AddField(
            model_name='movimientocuentacorriente',
            name='recibo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_cc', to='administrar.recibo'),
        ),
    ]
