# Generated by Django 5.2.8 on 2025-12-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0029_movimientocuentacorriente_venta_recibo_itemrecibo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrecibo',
            name='retencion_numero',
            field=models.CharField(blank=True, help_text='Número de certificado', max_length=50),
        ),
        migrations.AddField(
            model_name='itemrecibo',
            name='retencion_tipo',
            field=models.CharField(blank=True, choices=[('IIBB', 'Ingresos Brutos'), ('GANANCIAS', 'Ganancias'), ('SUSS', 'SUSS'), ('IVA', 'IVA'), ('OTRA', 'Otra')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itemrecibo',
            name='forma_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('TRANSFERENCIA', 'Transferencia'), ('DEBITO', 'Tarjeta de Débito'), ('CREDITO', 'Tarjeta de Crédito'), ('RETENCION', 'Retención Impositiva'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
