# Generated by Django 5.2.8 on 2025-12-08 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0030_itemrecibo_retencion_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('cbu', models.CharField(blank=True, max_length=22)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos'), ('USD', 'Dólares')], default='ARS', max_length=3)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConciliacionBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('saldo_banco', models.DecimalField(decimal_places=2, help_text='Saldo según extracto bancario', max_digits=12)),
                ('saldo_sistema', models.DecimalField(decimal_places=2, help_text='Saldo calculado en sistema', max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=15)),
                ('fecha_proceso', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrar.cuentabancaria')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('conciliado', models.BooleanField(default=False)),
                ('fecha_conciliado', models.DateField(blank=True, null=True)),
                ('referencia_interna', models.CharField(blank=True, help_text='Referencia a Cheque, Transferencia, etc.', max_length=100)),
                ('conciliacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_conciliados', to='administrar.conciliacionbancaria')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='administrar.cuentabancaria')),
            ],
        ),
    ]
