# Generated by Django 5.2.8 on 2025-12-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0031_cuentabancaria_conciliacionbancaria_movimientobanco'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Imagen de Perfil'),
        ),
    ]
