# Generated by Django 5.2.8 on 2025-12-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0033_presupuesto_detallepresupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='medio_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('CHEQUE', 'Cheque'), ('CTACTE', 'Cuenta Corriente'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=10),
        ),
    ]
