# Generated by Django 5.2.8 on 2026-01-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0034_venta_medio_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='alias',
            field=models.CharField(blank=True, max_length=100, verbose_name='Alias CBU'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cbu',
            field=models.CharField(blank=True, max_length=22, verbose_name='CBU'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='condicion_fiscal',
            field=models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MO', 'Monotributista'), ('EX', 'Exento'), ('CF', 'Consumidor Final')], default='CF', max_length=2),
        ),
    ]
