# Generated by Django 5.2.8 on 2026-01-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0036_movimientocaja_usuario_cajadiaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='items_por_pagina',
            field=models.IntegerField(default=10, verbose_name='Items por Página'),
        ),
    ]
