# Generated by Django 5.2.8 on 2026-01-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0037_empresa_items_por_pagina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notadebito',
            name='tipo_comprobante',
            field=models.CharField(choices=[('NDA', 'Nota Débito A'), ('NDB', 'Nota Débito B'), ('NDC', 'Nota Débito C')], max_length=3),
        ),
    ]
