# Generated by Django 5.2.8 on 2026-01-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0038_alter_notadebito_tipo_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='acceso_bancos',
            field=models.BooleanField(default=False, verbose_name='Acceso a Bancos'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='acceso_ctacte',
            field=models.BooleanField(default=False, verbose_name='Acceso a Ctas. Corrientes'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='acceso_pedidos',
            field=models.BooleanField(default=False, verbose_name='Acceso a Pedidos'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='acceso_remitos',
            field=models.BooleanField(default=False, verbose_name='Acceso a Remitos'),
        ),
    ]
