# Generated by Django 5.2.8 on 2026-01-11 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0039_perfilusuario_acceso_bancos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuesto_origen', to='administrar.pedido'),
        ),
    ]
