# Generated by Django 5.2.8 on 2026-01-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0040_presupuesto_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='actualizar_precios_compra',
            field=models.BooleanField(default=False, verbose_name='Actualizar Precios en Compra'),
        ),
    ]
