# Generated by Django 5.2.8 on 2026-01-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0041_empresa_actualizar_precios_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='alerta_stock_minimo',
            field=models.BooleanField(default=True, verbose_name='Alerta de Stock Mínimo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='margen_ganancia_defecto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Margen de Ganancia por Defecto (%)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='permitir_stock_negativo',
            field=models.BooleanField(default=False, verbose_name='Permitir Stock Negativo'),
        ),
    ]
