# Generated by Django 5.2.8 on 2026-01-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0042_empresa_alerta_stock_minimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='metodo_ganancia',
            field=models.CharField(choices=[('MARKUP', 'Markup (Sobre Costo)'), ('MARGIN', 'Margen Real (Sobre Venta)')], default='MARKUP', max_length=10, verbose_name='Método de Cálculo de Ganancia'),
        ),
    ]
