# Generated by Django 5.2.8 on 2026-01-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0043_empresa_metodo_ganancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='auto_foco_codigo_barras',
            field=models.BooleanField(default=False, verbose_name='Auto-Foco Código de Barras'),
        ),
    ]
