# Generated by Django 5.2.8 on 2026-01-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0044_empresa_auto_foco_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='compra',
            name='neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='empresa',
            name='discriminar_iva_compras',
            field=models.BooleanField(default=False, verbose_name='Discriminar IVA en Compras'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='redondeo_precios',
            field=models.IntegerField(choices=[(1, 'Sin Redondeo'), (10, 'Múltiplos de 10'), (50, 'Múltiplos de 50'), (100, 'Múltiplos de 100')], default=1, verbose_name='Redondeo de Precios'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='iva_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='neto_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
