# Generated by Django 5.2.8 on 2026-01-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0045_compra_iva_compra_neto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='iva_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='empresa',
            name='discriminar_iva_ventas',
            field=models.BooleanField(default=False, verbose_name='Discriminar IVA en Ventas'),
        ),
        migrations.AddField(
            model_name='producto',
            name='iva_alicuota',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='Alícuota IVA (%)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='iva_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
