# Generated by Django 5.2.8 on 2026-01-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0046_detalleventa_iva_amount_detalleventa_neto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nombre_fantasia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre de Fantasía'),
        ),
    ]
