# Generated by Django 5.2.8 on 2026-01-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0047_empresa_nombre_fantasia'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ocultar_barra_scroll',
            field=models.BooleanField(default=True, verbose_name='Ocultar Barra de Scroll en Menú'),
        ),
    ]
