# Generated by Django 5.2.8 on 2026-01-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0048_empresa_ocultar_barra_scroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
