# Generated by Django 5.2.8 on 2026-01-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0049_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='comportamiento_codigo_barras',
            field=models.CharField(choices=[('DEFAULT', 'Normal (Seleccionar y Focus Cantidad)'), ('CANTIDAD', 'Saltar a Cantidad'), ('DIRECTO', 'Agregar Directamente (Qty=1)')], default='DEFAULT', max_length=20, verbose_name='Comportamiento Escaneo Código de Barras'),
        ),
    ]
