# Generated by Django 5.2.8 on 2026-01-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0050_empresa_comportamiento_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono'),
        ),
    ]
