# Generated by Django 5.2.8 on 2026-01-24 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0051_perfilusuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocuentacorrienteproveedor',
            name='recibo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_cc_proveedor', to='administrar.recibo'),
        ),
    ]
