# Generated by Django 5.2.8 on 2026-01-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0052_movimientocuentacorrienteproveedor_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='backup_google_drive_credentials',
            field=models.TextField(blank=True, verbose_name='Credenciales Google Drive (JSON)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='backup_google_drive_enabled',
            field=models.BooleanField(default=False, verbose_name='Habilitar Google Drive'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='backup_google_drive_folder_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Carpeta Google Drive'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='backup_local_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ruta de Backups Locales'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='tipo',
            field=models.CharField(choices=[('DB', 'Base de Datos'), ('SOLO_SISTEMA', 'Solo Archivos de Sistema'), ('SISTEMA', 'Archivos de Sistema')], default='DB', max_length=20),
        ),
    ]
