# Generated by Django 5.2.8 on 2026-01-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0053_empresa_backup_google_drive_credentials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='iva_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='iva_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
