# Generated by Django 5.2.8 on 2026-01-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0054_detallecompra_iva_amount_detallecompra_neto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='percepcion_iibb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='compra',
            name='percepcion_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='compra',
            name='retencion_iibb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='compra',
            name='retencion_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='percepcion_iibb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='percepcion_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
