# Generated by Django 5.2.8 on 2026-01-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0055_compra_percepcion_iibb_compra_percepcion_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='percepcion_iibb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='percepcion_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='retencion_iibb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='retencion_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
