# Generated by Django 5.2.8 on 2026-01-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0056_ordencompra_percepcion_iibb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ancho_contenido',
            field=models.CharField(choices=[('max-w-7xl', 'Estándar (1280px)'), ('max-w-5xl', 'Compacto (1024px)'), ('max-w-screen-2xl', 'Amplio (1536px)'), ('max-w-full', 'Pantalla Completa (Fluido)')], default='max-w-7xl', max_length=20, verbose_name='Ancho del Contenido'),
        ),
    ]
