# Generated by Django 5.2.8 on 2026-02-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0057_empresa_ancho_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ocultar_scroll_tablas',
            field=models.BooleanField(default=False, verbose_name='Ocultar Scroll en Tablas'),
        ),
    ]
