# Generated by Django 5.2.8 on 2026-02-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0058_empresa_ocultar_scroll_tablas'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='acceso_auditoria',
            field=models.BooleanField(default=False, verbose_name='Acceso a Auditoría'),
        ),
    ]
