# Generated by Django 5.2.8 on 2026-02-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0059_perfilusuario_acceso_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='comportamiento_lector_compras',
            field=models.CharField(choices=[('DEFAULT', 'Normal (Seleccionar y Focus Cantidad)'), ('CANTIDAD', 'Saltar a Cantidad'), ('DIRECTO', 'Agregar Directamente (Qty=1)')], default='CANTIDAD', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='comportamiento_lector_pedidos',
            field=models.CharField(choices=[('DEFAULT', 'Normal (Seleccionar y Focus Cantidad)'), ('CANTIDAD', 'Saltar a Cantidad'), ('DIRECTO', 'Agregar Directamente (Qty=1)')], default='CANTIDAD', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='comportamiento_lector_presupuestos',
            field=models.CharField(choices=[('DEFAULT', 'Normal (Seleccionar y Focus Cantidad)'), ('CANTIDAD', 'Saltar a Cantidad'), ('DIRECTO', 'Agregar Directamente (Qty=1)')], default='CANTIDAD', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='comportamiento_lector_ventas',
            field=models.CharField(choices=[('DEFAULT', 'Normal (Seleccionar y Focus Cantidad)'), ('CANTIDAD', 'Saltar a Cantidad'), ('DIRECTO', 'Agregar Directamente (Qty=1)')], default='DIRECTO', max_length=20),
        ),
    ]
