# Generated by Django 5.2.8 on 2026-02-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0060_empresa_comportamiento_lector_compras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='comportamiento_lector_remitos',
            field=models.CharField(choices=[('DEFAULT', 'Normal (Seleccionar y Focus Cantidad)'), ('CANTIDAD', 'Saltar a Cantidad'), ('DIRECTO', 'Agregar Directamente (Qty=1)')], default='CANTIDAD', max_length=20),
        ),
    ]
