# Generated by Django 5.2.8 on 2026-02-02 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0061_empresa_comportamiento_lector_remitos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='comportamiento_lector_remitos',
        ),
    ]
